In [171]:
import pandas as pd
import numpy as np

In [172]:
df=pd.read_csv("E:\\pandas\\sales.csv")
print(df)

     Transaction ID      Item Quantity Price Per Unit Total Spent  \
0       TXN_1961373    Coffee        2            2.0         4.0
1       TXN_4977031      Cake        4            3.0        12.0
2       TXN_4271903    Cookie        4            1.0       ERROR
3       TXN_7034554     Salad        2            5.0        10.0
4       TXN_3160411    Coffee        2            2.0         4.0
...             ...       ...      ...            ...         ...
9995    TXN_7672686    Coffee        2            2.0         4.0
9996    TXN_9659401       NaN        3            NaN         3.0
9997    TXN_5255387    Coffee        4            2.0         8.0
9998    TXN_7695629    Cookie        3            NaN         3.0
9999    TXN_6170729  Sandwich        3            4.0        12.0

      Payment Method  Location Transaction Date
0        Credit Card  Takeaway       2023-09-08
1               Cash  In-store       2023-05-16
2        Credit Card  In-store       2023-07-19
3            UNKNOWN   UNKNOWN       2023-04-27
4     Digital Wallet  In-store       2023-06-11
...              ...       ...              ...
9995             NaN   UNKNOWN       2023-08-30
9996  Digital Wallet       NaN       2023-06-02
9997  Digital Wallet       NaN       2023-03-02
9998  Digital Wallet       NaN       2023-12-02
9999            Cash  In-store       2023-11-07

[10000 rows x 8 columns]

In [173]:
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [174]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [175]:
df.tail()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [176]:

df.isna().sum()
df.isna().sum().sum()

np.int64(6826)

In [177]:
# drop na
df.dropna(inplace=True)

In [178]:
# chexk duplicate
df.duplicated()
df.duplicated().sum()

np.int64(0)

In [179]:
df.drop_duplicates(inplace=True)

1-Removing values
2-Changing datatypes

In [180]:
# df["Transaction ID"].unique() ye return kre ga array
df["Transaction ID"].unique().tolist()

['TXN_1961373',
 'TXN_4977031',
 'TXN_4271903',
 'TXN_7034554',
 'TXN_3160411',
 'TXN_4433211',
 'TXN_6699534',
 'TXN_2548360',
 'TXN_3051279',
 'TXN_7619095',
 'TXN_2847255',
 'TXN_6769710',
 'TXN_8876618',
 'TXN_3709394',
 'TXN_3522028',
 'TXN_3567645',
 'TXN_5132361',
 'TXN_9400181',
 'TXN_5183041',
 'TXN_5695074',
 'TXN_7640952',
 'TXN_8927252',
 'TXN_8853997',
 'TXN_9130559',
 'TXN_1080432',
 'TXN_8078640',
 'TXN_6342161',
 'TXN_8614868',
 'TXN_5522862',
 'TXN_2080895',
 'TXN_6421134',
 'TXN_3068204',
 'TXN_8471743',
 'TXN_2621580',
 'TXN_4726376',
 'TXN_1900620',
 'TXN_6420335',
 'TXN_3829165',
 'TXN_3748616',
 'TXN_5266394',
 'TXN_8718498',
 'TXN_9487821',
 'TXN_8976658',
 'TXN_6289610',
 'TXN_8268061',
 'TXN_5220895',
 'TXN_3085509',
 'TXN_9999113',
 'TXN_8779771',
 'TXN_3808639',
 'TXN_6955416',
 'TXN_3775339',
 'TXN_4358673',
 'TXN_1001832',
 'TXN_2148617',
 'TXN_4368416',
 'TXN_6258471',
 'TXN_4685453',
 'TXN_9096052',
 'TXN_5916991',
 'TXN_3407169',
 'TXN_2181545',
 'TXN_1150033',
 'TXN_8700451',
 'TXN_6380550',
 'TXN_4885518',
 'TXN_8729570',
 'TXN_9336980',
 'TXN_5072031',
 'TXN_6541415',
 'TXN_1928241',
 'TXN_4283157',
 'TXN_7965998',
 'TXN_9238666',
 'TXN_3226832',
 'TXN_1648671',
 'TXN_4062737',
 'TXN_9249507',
 'TXN_9836934',
 'TXN_3925836',
 'TXN_3978874',
 'TXN_1136554',
 'TXN_8007337',
 'TXN_3831848',
 'TXN_5365809',
 'TXN_6629480',
 'TXN_3833797',
 'TXN_7412722',
 'TXN_6000201',
 'TXN_3800182',
 'TXN_2950680',
 'TXN_4088917',
 'TXN_3779366',
 'TXN_7724048',
 'TXN_3171373',
 'TXN_8693704',
 'TXN_3857960',
 'TXN_9250710',
 'TXN_9879996',
 'TXN_4291940',
 'TXN_5761073',
 'TXN_5047447',
 'TXN_6623508',
 'TXN_9350833',
 'TXN_7031118',
 'TXN_2230167',
 'TXN_1721827',
 'TXN_6334895',
 'TXN_7077119',
 'TXN_3205009',
 'TXN_3786188',
 'TXN_9642066',
 'TXN_6714420',
 'TXN_6616971',
 'TXN_7803615',
 'TXN_3544789',
 'TXN_1583597',
 'TXN_8472308',
 'TXN_1967565',
 'TXN_2029497',
 'TXN_7852990',
 'TXN_2059647',
 'TXN_2485183',
 'TXN_7374846',
 'TXN_9401522',
 'TXN_8250651',
 'TXN_8982764',
 'TXN_1153869',
 'TXN_3229409',
 'TXN_6371987',
 'TXN_2084377',
 'TXN_1842675',
 'TXN_7557340',
 'TXN_1157817',
 'TXN_2020318',
 'TXN_5307411',
 'TXN_1289133',
 'TXN_2031459',
 'TXN_1623966',
 'TXN_4912930',
 'TXN_3723007',
 'TXN_7496926',
 'TXN_7559388',
 'TXN_8540499',
 'TXN_6795640',
 'TXN_6702428',
 'TXN_1259671',
 'TXN_5523450',
 'TXN_7838964',
 'TXN_7275407',
 'TXN_9472241',
 'TXN_4473352',
 'TXN_1846004',
 'TXN_7773968',
 'TXN_9081088',
 'TXN_8559167',
 'TXN_1130191',
 'TXN_1040764',
 'TXN_5457133',
 'TXN_2100697',
 'TXN_7676968',
 'TXN_4134594',
 'TXN_5079340',
 'TXN_1380601',
 'TXN_7569615',
 'TXN_2052395',
 'TXN_9065402',
 'TXN_2635532',
 'TXN_8256593',
 'TXN_9271457',
 'TXN_5392603',
 'TXN_9263299',
 'TXN_1436343',
 'TXN_7480234',
 'TXN_3283097',
 'TXN_2633602',
 'TXN_3665733',
 'TXN_1454467',
 'TXN_8224079',
 'TXN_1916339',
 'TXN_8611035',
 'TXN_3595735',
 'TXN_3668051',
 'TXN_6169633',
 'TXN_7050740',
 'TXN_4518102',
 'TXN_5939055',
 'TXN_7809183',
 'TXN_6071202',
 'TXN_3666858',
 'TXN_5499915',
 'TXN_8089522',
 'TXN_1564754',
 'TXN_1824506',
 'TXN_3229758',
 'TXN_1002457',
 'TXN_4732351',
 'TXN_8049191',
 'TXN_4980036',
 'TXN_3022839',
 'TXN_7701070',
 'TXN_8048037',
 'TXN_1887522',
 'TXN_7555408',
 'TXN_9552845',
 'TXN_6769465',
 'TXN_3871837',
 'TXN_4980282',
 'TXN_3580786',
 'TXN_2508476',
 'TXN_1325631',
 'TXN_8209125',
 'TXN_3730415',
 'TXN_4134253',
 'TXN_3256497',
 'TXN_7919440',
 'TXN_7558641',
 'TXN_3234877',
 'TXN_6368719',
 'TXN_8852585',
 'TXN_9201010',
 'TXN_7817014',
 'TXN_3607652',
 'TXN_8502094',
 'TXN_9068244',
 'TXN_7633490',
 'TXN_9292230',
 'TXN_1664665',
 'TXN_8006668',
 'TXN_3560062',
 'TXN_6360132',
 'TXN_7864939',
 'TXN_3740963',
 'TXN_6063966',
 'TXN_3779640',
 'TXN_8136881',
 'TXN_3981449',
 'TXN_5427506',
 'TXN_2641386',
 'TXN_1485417',
 'TXN_4033802',
 'TXN_7752124',
 'TXN_9762324',
 'TXN_4183823',
 'TXN_4696439',
 'TXN_8826983',
 'TXN_2947822',
 'TXN_1330506',
 'TXN_2493446',
 'TXN_4538354',
 'TXN_2690314',
 'TXN_2968827',
 'TXN_1387401',
 'TXN_3917193',
 'TXN_2062854',
 'TXN_4075863',
 'TXN_5624860',
 'TXN_3381656',
 'TXN_1183995',
 'TXN_9452225',
 'TXN_5813015',
 'TXN_3789752',
 'TXN_7578769',
 'TXN_3515664',
 'TXN_6422433',
 'TXN_4669664',
 'TXN_1109715',
 'TXN_5904646',
 'TXN_2213556',
 'TXN_3826038',
 'TXN_7380277',
 'TXN_9266394',
 'TXN_5448157',
 'TXN_6152588',
 'TXN_5739806',
 'TXN_9228978',
 'TXN_1556652',
 'TXN_7353972',
 'TXN_1124753',
 'TXN_7611120',
 'TXN_2106959',
 'TXN_6316959',
 'TXN_2265984',
 'TXN_6352917',
 'TXN_1123138',
 'TXN_9212503',
 'TXN_2806243',
 'TXN_3286932',
 'TXN_3481470',
 'TXN_9907327',
 'TXN_3469469',
 'TXN_2681833',
 'TXN_4998786',
 'TXN_2126408',
 'TXN_8958593',
 'TXN_2383598',
 'TXN_2211685',
 'TXN_5933480',
 'TXN_4364091',
 'TXN_5447508',
 'TXN_5686113',
 'TXN_9239779',
 'TXN_3397609',
 'TXN_9347203',
 'TXN_3383926',
 'TXN_6905718',
 'TXN_7993951',
 'TXN_9097641',
 'TXN_8536115',
 'TXN_2915281',
 'TXN_3468006',
 'TXN_7604541',
 'TXN_7806146',
 'TXN_9238689',
 'TXN_2601689',
 'TXN_6428182',
 'TXN_6830557',
 'TXN_6371264',
 'TXN_4663299',
 'TXN_9236713',
 'TXN_4690833',
 'TXN_7946489',
 'TXN_8661288',
 'TXN_2866147',
 'TXN_5637677',
 'TXN_6111710',
 'TXN_1773873',
 'TXN_4570711',
 'TXN_5242469',
 'TXN_1655100',
 'TXN_1526864',
 'TXN_9866728',
 'TXN_1706201',
 'TXN_2498488',
 'TXN_5387067',
 'TXN_4431179',
 'TXN_2108894',
 'TXN_6347472',
 'TXN_8345723',
 'TXN_9989415',
 'TXN_1932897',
 'TXN_2178964',
 'TXN_5213542',
 'TXN_6581437',
 'TXN_1347965',
 'TXN_6128621',
 'TXN_1349738',
 'TXN_4512118',
 'TXN_5763254',
 'TXN_4961655',
 'TXN_5595352',
 'TXN_2070818',
 'TXN_1090854',
 'TXN_1869814',
 'TXN_8296518',
 'TXN_6910915',
 'TXN_5787508',
 'TXN_5229169',
 'TXN_4074732',
 'TXN_5576265',
 'TXN_5408625',
 'TXN_1046394',
 'TXN_2269396',
 'TXN_9263967',
 'TXN_2914088',
 'TXN_6571898',
 'TXN_4015710',
 'TXN_2108486',
 'TXN_4953450',
 'TXN_5315441',
 'TXN_9196322',
 'TXN_5931292',
 'TXN_8776606',
 'TXN_2393500',
 'TXN_9738758',
 'TXN_7838465',
 'TXN_2447261',
 'TXN_6609947',
 'TXN_2611990',
 'TXN_1460963',
 'TXN_2840323',
 'TXN_6691767',
 'TXN_7280191',
 'TXN_6932070',
 'TXN_5489408',
 'TXN_4640977',
 'TXN_7896721',
 'TXN_7906197',
 'TXN_8066743',
 'TXN_9658677',
 'TXN_6376175',
 'TXN_4912458',
 'TXN_2855581',
 'TXN_7585348',
 'TXN_8249251',
 'TXN_4005014',
 'TXN_3106215',
 'TXN_4478185',
 'TXN_7815651',
 'TXN_3461209',
 'TXN_1026827',
 'TXN_4479052',
 'TXN_5369555',
 'TXN_8187656',
 'TXN_6463415',
 'TXN_4944121',
 'TXN_4634772',
 'TXN_8034156',
 'TXN_2163229',
 'TXN_4109764',
 'TXN_1343750',
 'TXN_8022689',
 'TXN_9392028',
 'TXN_8503406',
 'TXN_9402247',
 'TXN_2416816',
 'TXN_1778707',
 'TXN_3110343',
 'TXN_2820693',
 'TXN_3746260',
 'TXN_3725837',
 'TXN_4594922',
 'TXN_5163686',
 'TXN_2826603',
 'TXN_2526667',
 'TXN_3760598',
 'TXN_7679707',
 'TXN_3831364',
 'TXN_5038513',
 'TXN_5007619',
 'TXN_8460786',
 'TXN_7078232',
 'TXN_9625287',
 'TXN_7337979',
 'TXN_5630457',
 'TXN_4487966',
 'TXN_2190793',
 'TXN_3663712',
 'TXN_9140598',
 'TXN_4316299',
 'TXN_3696194',
 'TXN_2964638',
 'TXN_8336656',
 'TXN_2024121',
 'TXN_6287890',
 'TXN_4712887',
 'TXN_5447694',
 'TXN_5350401',
 'TXN_1866028',
 'TXN_8379141',
 'TXN_9152264',
 'TXN_3794585',
 'TXN_3856427',
 'TXN_9890874',
 'TXN_4874685',
 'TXN_6024625',
 'TXN_7470910',
 'TXN_9911345',
 'TXN_1116119',
 'TXN_3471223',
 'TXN_8692653',
 'TXN_5021925',
 'TXN_1104849',
 'TXN_7764154',
 'TXN_2178735',
 'TXN_5014959',
 'TXN_5348445',
 'TXN_7215985',
 'TXN_7448296',
 'TXN_3542902',
 'TXN_1494608',
 'TXN_7615147',
 'TXN_5892508',
 'TXN_5546684',
 'TXN_6402128',
 'TXN_5009706',
 'TXN_1991104',
 'TXN_3380698',
 'TXN_2336708',
 'TXN_1512118',
 'TXN_6077816',
 'TXN_4033888',
 'TXN_9218683',
 'TXN_2153529',
 'TXN_7880148',
 'TXN_2482129',
 'TXN_4187420',
 'TXN_9553579',
 'TXN_3854285',
 'TXN_5614488',
 'TXN_6187083',
 'TXN_6868182',
 'TXN_6035534',
 'TXN_8781128',
 'TXN_7201724',
 'TXN_3616362',
 'TXN_6113876',
 'TXN_6007079',
 'TXN_3163383',
 'TXN_4907812',
 'TXN_6450138',
 'TXN_9874588',
 'TXN_5442610',
 'TXN_2155368',
 'TXN_5236892',
 'TXN_1324930',
 'TXN_7085875',
 'TXN_6057379',
 'TXN_9313535',
 'TXN_9626053',
 'TXN_5583534',
 'TXN_1438257',
 'TXN_4257830',
 'TXN_4315988',
 'TXN_3963927',
 'TXN_7023528',
 'TXN_9124680',
 'TXN_7853635',
 'TXN_3516263',
 'TXN_1591640',
 'TXN_7401710',
 'TXN_1697018',
 'TXN_2667225',
 'TXN_3152531',
 'TXN_7527249',
 'TXN_9159212',
 'TXN_3282436',
 'TXN_8465274',
 'TXN_8330446',
 'TXN_1282260',
 'TXN_9582716',
 'TXN_9769410',
 'TXN_9603131',
 'TXN_1437083',
 'TXN_2413626',
 'TXN_3392848',
 'TXN_7027905',
 'TXN_8808034',
 'TXN_1663113',
 'TXN_1544070',
 'TXN_6189334',
 'TXN_3412490',
 'TXN_6908287',
 'TXN_6829707',
 'TXN_7303706',
 'TXN_1730647',
 'TXN_9691018',
 'TXN_4936135',
 'TXN_8808631',
 'TXN_8703212',
 'TXN_4496665',
 'TXN_8209794',
 'TXN_3330687',
 'TXN_9822317',
 'TXN_5354746',
 'TXN_3736798',
 'TXN_9102030',
 'TXN_6719521',
 'TXN_5386752',
 'TXN_1022523',
 'TXN_9906002',
 'TXN_6202015',
 'TXN_6928137',
 'TXN_5913013',
 'TXN_7433269',
 'TXN_2633600',
 'TXN_4631695',
 'TXN_4617771',
 'TXN_1741325',
 'TXN_9983356',
 'TXN_8964527',
 'TXN_9408993',
 'TXN_7810285',
 'TXN_1961595',
 'TXN_4179561',
 'TXN_9056301',
 'TXN_8530924',
 'TXN_6910030',
 'TXN_7609781',
 'TXN_8398059',
 'TXN_3755379',
 'TXN_1792573',
 'TXN_2923987',
 'TXN_1789644',
 'TXN_9991225',
 'TXN_8734476',
 'TXN_6471962',
 'TXN_4792702',
 'TXN_3572190',
 'TXN_6791398',
 'TXN_8361255',
 'TXN_5858988',
 'TXN_1476066',
 'TXN_6078834',
 'TXN_8186625',
 'TXN_2946829',
 'TXN_8750849',
 'TXN_1973716',
 'TXN_1105589',
 'TXN_6915192',
 'TXN_4988665',
 'TXN_2482363',
 'TXN_5412834',
 'TXN_1389258',
 'TXN_8300706',
 'TXN_8076559',
 'TXN_4310310',
 'TXN_2916209',
 'TXN_6411716',
 'TXN_1154979',
 'TXN_6129205',
 'TXN_4832513',
 'TXN_1180969',
 'TXN_4356223',
 'TXN_7216161',
 'TXN_2426782',
 'TXN_2471972',
 'TXN_4651514',
 'TXN_6555617',
 'TXN_6899834',
 'TXN_8817239',
 'TXN_7538570',
 'TXN_8789116',
 'TXN_8930109',
 'TXN_9799798',
 'TXN_5067373',
 'TXN_5755839',
 'TXN_1681153',
 'TXN_4255503',
 'TXN_2385697',
 'TXN_9151321',
 'TXN_1602799',
 'TXN_9579181',
 'TXN_7391267',
 'TXN_1388606',
 'TXN_2336857',
 'TXN_9526867',
 'TXN_4427348',
 'TXN_5792655',
 'TXN_7782538',
 'TXN_6404763',
 'TXN_5290522',
 'TXN_4915908',
 'TXN_7146613',
 'TXN_9996968',
 'TXN_7043825',
 'TXN_2195630',
 'TXN_2539318',
 'TXN_5788769',
 'TXN_3628056',
 'TXN_5856820',
 'TXN_9354616',
 'TXN_5268203',
 'TXN_3483570',
 'TXN_7406393',
 'TXN_5226635',
 'TXN_9278992',
 'TXN_4369292',
 'TXN_2952715',
 'TXN_3912727',
 'TXN_6983139',
 'TXN_5977414',
 'TXN_8517379',
 'TXN_9074075',
 'TXN_5121322',
 'TXN_8550184',
 'TXN_3712466',
 'TXN_7590801',
 'TXN_6962242',
 'TXN_5780931',
 'TXN_6177865',
 'TXN_8115752',
 'TXN_4889269',
 'TXN_8808162',
 'TXN_4548466',
 'TXN_9728454',
 'TXN_5750278',
 'TXN_5944206',
 'TXN_9212178',
 'TXN_9201212',
 'TXN_7055260',
 'TXN_4773465',
 'TXN_9087344',
 'TXN_1757340',
 'TXN_9975321',
 'TXN_9390740',
 'TXN_4928254',
 'TXN_5191642',
 'TXN_9117434',
 'TXN_1082421',
 'TXN_5402385',
 'TXN_1494502',
 'TXN_9333347',
 'TXN_6451377',
 'TXN_2142961',
 'TXN_5575561',
 'TXN_1007347',
 'TXN_6731518',
 'TXN_3455702',
 'TXN_7794561',
 'TXN_8908193',
 'TXN_7688625',
 'TXN_4323570',
 'TXN_8831924',
 'TXN_1360998',
 'TXN_4657842',
 'TXN_8149585',
 'TXN_9047278',
 'TXN_1931404',
 'TXN_4516901',
 'TXN_6817795',
 'TXN_6809170',
 'TXN_7365744',
 'TXN_9847116',
 'TXN_8356338',
 'TXN_4413506',
 'TXN_1057209',
 'TXN_9534685',
 'TXN_4737392',
 'TXN_9538738',
 'TXN_1854102',
 'TXN_8837375',
 'TXN_7950226',
 'TXN_9086541',
 'TXN_1817596',
 'TXN_8017969',
 'TXN_6667388',
 'TXN_9425645',
 'TXN_4692976',
 'TXN_6747376',
 'TXN_9662568',
 'TXN_3717372',
 'TXN_9899571',
 'TXN_5692316',
 'TXN_2062269',
 'TXN_8313892',
 'TXN_4083736',
 'TXN_6712994',
 'TXN_6257776',
 'TXN_4430176',
 'TXN_6073195',
 'TXN_4291132',
 'TXN_1622123',
 'TXN_2878078',
 'TXN_7134579',
 'TXN_6921057',
 'TXN_2335088',
 'TXN_9778859',
 'TXN_6386662',
 'TXN_5491825',
 'TXN_3326110',
 'TXN_5455079',
 'TXN_5526475',
 'TXN_3800253',
 'TXN_2091128',
 'TXN_4134478',
 'TXN_9522899',
 'TXN_7296498',
 'TXN_2488987',
 'TXN_1865735',
 'TXN_5342589',
 'TXN_1987212',
 'TXN_5303275',
 'TXN_9316158',
 'TXN_8207244',
 'TXN_2346001',
 'TXN_2814866',
 'TXN_2560137',
 'TXN_7350571',
 'TXN_3915802',
 'TXN_1785371',
 'TXN_6441650',
 'TXN_2493262',
 'TXN_3257591',
 'TXN_6038791',
 'TXN_1335337',
 'TXN_2275914',
 'TXN_6258276',
 'TXN_2340312',
 'TXN_7730388',
 'TXN_6363897',
 'TXN_1893222',
 'TXN_9491912',
 'TXN_6992164',
 'TXN_5624179',
 'TXN_3450160',
 'TXN_4075432',
 'TXN_2023802',
 'TXN_6745832',
 'TXN_8182245',
 'TXN_3970335',
 'TXN_7100596',
 'TXN_1481116',
 'TXN_9454212',
 'TXN_3648327',
 'TXN_6188394',
 'TXN_2553803',
 'TXN_8018479',
 'TXN_9465300',
 'TXN_3046108',
 'TXN_4454198',
 'TXN_5855756',
 'TXN_5182399',
 'TXN_6758675',
 'TXN_1962275',
 'TXN_6668414',
 'TXN_8715122',
 'TXN_7681072',
 'TXN_8789986',
 'TXN_8382825',
 'TXN_4486700',
 'TXN_5085328',
 'TXN_6191769',
 'TXN_6110386',
 'TXN_9169536',
 'TXN_8257774',
 'TXN_3873718',
 'TXN_1225638',
 'TXN_5508620',
 'TXN_7864080',
 'TXN_2463115',
 'TXN_9948425',
 'TXN_6762172',
 'TXN_5591967',
 'TXN_5861158',
 'TXN_7501002',
 'TXN_2848654',
 'TXN_3034652',
 'TXN_2710779',
 'TXN_2333576',
 'TXN_6607568',
 'TXN_9837568',
 'TXN_9603263',
 'TXN_9425610',
 'TXN_9749333',
 'TXN_7376092',
 'TXN_8278982',
 'TXN_7686476',
 'TXN_4283563',
 'TXN_3981000',
 'TXN_7068653',
 'TXN_7367474',
 'TXN_7551097',
 'TXN_1498343',
 'TXN_3107619',
 'TXN_7411993',
 'TXN_4679593',
 'TXN_1630051',
 'TXN_2566258',
 'TXN_5785600',
 'TXN_4864206',
 'TXN_2640727',
 'TXN_5113993',
 'TXN_2192787',
 'TXN_2127588',
 'TXN_8108748',
 'TXN_5538713',
 'TXN_5949811',
 'TXN_2565449',
 'TXN_9224501',
 'TXN_5767393',
 'TXN_9287133',
 'TXN_7134064',
 'TXN_5486063',
 'TXN_2285849',
 'TXN_9577271',
 'TXN_2624121',
 'TXN_7868879',
 'TXN_8321225',
 'TXN_6243519',
 'TXN_8668901',
 'TXN_4903004',
 'TXN_2195218',
 'TXN_9678108',
 'TXN_7362525',
 'TXN_2161341',
 'TXN_8753888',
 'TXN_2815691',
 'TXN_8956534',
 'TXN_7957208',
 'TXN_1749105',
 'TXN_1248266',
 'TXN_5331122',
 'TXN_1227800',
 'TXN_2699583',
 'TXN_2156218',
 'TXN_4894699',
 'TXN_5427338',
 'TXN_8631468',
 'TXN_7825457',
 'TXN_2378096',
 'TXN_3620110',
 'TXN_1005331',
 'TXN_1579182',
 'TXN_6843517',
 'TXN_9298053',
 'TXN_4987246',
 'TXN_2614545',
 'TXN_6236864',
 'TXN_7201361',
 'TXN_2229365',
 'TXN_5563675',
 'TXN_3520908',
 'TXN_7907499',
 'TXN_8360073',
 'TXN_4140167',
 'TXN_2690515',
 'TXN_2080682',
 'TXN_5661891',
 'TXN_1834831',
 'TXN_9834415',
 'TXN_4002629',
 'TXN_6551087',
 'TXN_1795044',
 'TXN_4735392',
 'TXN_8410712',
 'TXN_6009395',
 'TXN_3733753',
 'TXN_4084548',
 'TXN_7125945',
 'TXN_6746140',
 'TXN_9474082',
 'TXN_2810554',
 'TXN_5435751',
 'TXN_1339457',
 'TXN_5186460',
 'TXN_6885561',
 'TXN_6304285',
 'TXN_3653328',
 'TXN_3003876',
 'TXN_1270603',
 'TXN_2897115',
 'TXN_8916613',
 'TXN_9251292',
 'TXN_7770253',
 'TXN_5405799',
 'TXN_1701500',
 'TXN_6669163',
 'TXN_9695128',
 'TXN_8700156',
 'TXN_7192920',
 'TXN_4371760',
 'TXN_4468830',
 'TXN_3023841',
 'TXN_8793244',
 'TXN_5448602',
 'TXN_1346517',
 'TXN_9277534',
 'TXN_4946991',
 'TXN_2450799',
 'TXN_6145837',
 'TXN_5067056',
 'TXN_8453110',
 'TXN_6641409',
 'TXN_8626161',
 'TXN_7099050',
 'TXN_9565465',
 'TXN_6301600',
 'TXN_4784128',
 'TXN_5560205',
 'TXN_6346774',
 'TXN_6119798',
 'TXN_9793353',
 'TXN_2064360',
 'TXN_7125392',
 'TXN_2564219',
 'TXN_4488222',
 'TXN_3103967',
 'TXN_9853577',
 'TXN_4349597',
 'TXN_1672443',
 'TXN_6277500',
 'TXN_6671827',
 'TXN_5894676',
 'TXN_1411744',
 'TXN_4030197',
 'TXN_7276927',
 'TXN_3912836',
 'TXN_3833729',
 'TXN_7054393',
 'TXN_1395083',
 'TXN_8784653',
 'TXN_8308672',
 'TXN_3190959',
 'TXN_9301279',
 'TXN_8900751',
 'TXN_1667192',
 'TXN_6117497',
 'TXN_3818464',
 'TXN_2093816',
 'TXN_7415686',
 'TXN_7231548',
 'TXN_5956755',
 'TXN_3824443',
 'TXN_2621008',
 'TXN_8002886',
 'TXN_7694491',
 'TXN_7517996',
 'TXN_6047026',
 'TXN_2764962',
 ...]

In [181]:
pd.Series(df["Transaction ID"].unique().tolist()).str.startswith("TXN").value_counts()

True    4550
Name: count, dtype: int64

In [182]:
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9984,TXN_3142496,Smoothie,UNKNOWN,4.0,4.0,Cash,Takeaway,2023-07-27
9986,TXN_2858441,Sandwich,2,4.0,8.0,Credit Card,In-store,2023-12-14
9991,TXN_3897619,Sandwich,3,4.0,12.0,Cash,Takeaway,2023-02-24
9992,TXN_2739140,Smoothie,4,4.0,16.0,UNKNOWN,In-store,2023-07-05
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [183]:
df["Item"].unique()

array(['Coffee', 'Cake', 'Cookie', 'Salad', 'UNKNOWN', 'Sandwich',
       'Juice', 'Smoothie', 'ERROR', 'Tea'], dtype=object)

In [184]:
df["Quantity"].unique()

array(['2', '4', '3', '5', 'ERROR', '1', 'UNKNOWN'], dtype=object)

In [185]:
df["Price Per Unit"].unique()

array(['2.0', '3.0', '1.0', '5.0', '4.0', '1.5', 'UNKNOWN', 'ERROR'],
      dtype=object)

In [186]:
df["Payment Method"].unique()

array(['Credit Card', 'Cash', 'UNKNOWN', 'Digital Wallet', 'ERROR'],
      dtype=object)

In [187]:
df["Location"].unique()

array(['Takeaway', 'In-store', 'UNKNOWN', 'ERROR'], dtype=object)

In [188]:
df[~df.isin({"UNKNOWN", "ERROR"}).any(axis=1)]["Location"].unique()

array(['Takeaway', 'In-store'], dtype=object)

In [189]:
df[~df.isin({"UNKNOWN", "ERROR"}).any(axis=1)]

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
10,TXN_2548360,Salad,5,5.0,25.0,Cash,Takeaway,2023-11-07
12,TXN_7619095,Sandwich,2,4.0,8.0,Cash,In-store,2023-05-03
...,...,...,...,...,...,...,...,...
9975,TXN_9668108,Cake,1,3.0,3.0,Cash,In-store,2023-01-20
9979,TXN_9933628,Smoothie,5,4.0,20.0,Cash,In-store,2023-07-20
9986,TXN_2858441,Sandwich,2,4.0,8.0,Credit Card,In-store,2023-12-14
9991,TXN_3897619,Sandwich,3,4.0,12.0,Cash,Takeaway,2023-02-24
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [190]:
df.isin({"UNKNOWN", "ERROR"}).sum()

Transaction ID        0
Item                295
Quantity            146
Price Per Unit      168
Total Spent         155
Payment Method      346
Location            468
Transaction Date    128
dtype: int64

In [191]:
df.dtypes

Transaction ID      object
Item                object
Quantity            object
Price Per Unit      object
Total Spent         object
Payment Method      object
Location            object
Transaction Date    object
dtype: object

In [192]:
df["Transaction Date"]=pd.to_datetime(df["Transaction Date"], errors="coerce")

In [193]:
df.dtypes

Transaction ID              object
Item                        object
Quantity                    object
Price Per Unit              object
Total Spent                 object
Payment Method              object
Location                    object
Transaction Date    datetime64[ns]
dtype: object

In [ ]:
df.sort_values("Transaction Date")